# moonjin dev CI/CD

name: Deploy moonjin to Amazon ECS

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

# permissions:
#   contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.AWS_REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.AWS_REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.AWS_REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.AWS_REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            export PATH=`$PATH:/home/ubuntu/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
            cd moonjin-service
            git pull origin dev
            npm --help
            yarn install
            yarn preinstall
            yarn build:packages
            yarn build --filter=server
            cd apps/server
            pm2 kill
            yarn pm2:deploy
  
